# Generated by Django 4.1 on 2024-02-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='principal',
            field=models.CharField(default='John Doe', max_length=256),
            preserve_default=False,
        ),
    ]
