# Generated by Django 4.1 on 2024-02-24 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0002_school_principal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='principal',
            new_name='principle',
        ),
    ]
